language: python
dist: bionic
addons:
  apt:
    sources:
      - sourceline: 'ppa:s-ramacher/picnic'
    packages:
      - libpicnic-dev
      - pkg-config

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - nightly

matrix:
  allow_failures:
     - python: 3.9-dev
     - python: nightly

install:
  - pip install setuptools
  - pip install pkgconfig
  - pip install 'cython >= 0.28'
  - python setup.py build

script:
  - python setup.py test
